version: '3.5'
services:
  database:
    container_name: "blog_db"
    image: "mvertes/alpine-mongo:4.0.0-0"
    ports:
      - "27017:27017"  # host_port:container_port
    volumes:
      - type: volume
        source: db
        target: /data/db
    networks:
      - blog
  api:
    container_name: "blog_api"
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - database
    networks:
      - blog

networks:
  blog:
    name: blog
    driver: bridge

volumes:
  db: